name: MusicBox
main: net.shiroumi.musicbox.MusicBox
version: 1.5
description: Plays midi files.
commands:
  play:
    description: 音楽を再生します
    usage: /play <ファイル名>
  tune:
    description: ボックスステーションに接続し曲を聞ける様にします
    usage: /tune <in/out>